package lockfile

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	parserlock "github.com/github/actions-lockfile/go/pkg/lockfile"
	"github.com/github/gh-actions-lock/internal/dep"
	"golang.org/x/sync/singleflight"
)

// lockfileHeader is prepended to every write of the lockfile. It warns
// humans away from hand-editing and points them at the CLI that owns it.
const lockfileHeader = "# This file is machine-generated by `gh actions-lock`.\n" +
	"# Do not edit by hand; run `gh actions-lock` to update.\n" +
	"# Docs: https://gh.io/actions-lockfile\n"

// MetadataResolver fetches the owner/repo numeric IDs for a NWO. The store
// needs these to populate the dependencies: section on every write.
type MetadataResolver interface {
	RepoIDs(ctx context.Context, owner, repo string) (ownerID, repoID int64, err error)
}

// State wraps the on-disk dependency lockfile for the current invocation.
// Save garbage-collects orphan
// dependencies: entries — entries still referenced by an out-of-scope workflow are
// preserved, so partial invocations (e.g. `upgrade workflows/foo.yml`) stay
// noop on unrelated workflows.
//
// State is safe for concurrent use: Set/Save/Get/File/AllDeps/lookupIDs all
// take the same mutex, allowing parallel pin and upgrade workers to share
// a single store instance without external synchronization.
type State struct {
	mu       sync.Mutex
	lockPath string // full path to actions.lock on disk
	file     parserlock.File
	meta     MetadataResolver
	idCache  map[string][2]int64
	idSF     singleflight.Group
}

// ErrCorruptLockfile reports that a lockfile exists on disk but cannot be
// parsed (malformed YAML, unknown fields, or a dependency entry missing a
// required key). It is distinct from a missing lockfile (legitimately empty)
// and from a future-version lockfile (ErrFutureVersion). Callers decide
// recovery policy: prompt to delete and recreate, or fail loudly. Loading
// must never silently discard an unreadable lockfile and overwrite it.
var ErrCorruptLockfile = errors.New("lockfile is unreadable")

// LoadState reads the lockfile at repoRoot, returning an empty in-memory file
// when none exists on disk. A lockfile that exists but cannot be parsed is
// surfaced as ErrCorruptLockfile rather than being silently treated as empty.
func LoadState(repoRoot string, meta MetadataResolver) (*State, error) {
	return LoadStateAt(filepath.Join(repoRoot, parserlock.Path), meta)
}

// LoadStateAt reads the lockfile at the given path, returning an empty
// in-memory file when none exists on disk. Use this when the lockfile
// lives outside the standard .github/workflows/ location.
func LoadStateAt(lockfilePath string, meta MetadataResolver) (*State, error) {
	contents, err := os.ReadFile(lockfilePath)

	var file parserlock.File
	switch {
	case err == nil:
		file, err = parserlock.Parse(contents)
		if err != nil {
			// A future-version lockfile (written by a newer binary) must
			// surface to the user — silently overwriting it would destroy
			// pins this binary cannot interpret.
			//
			// The standalone parser emits a tool-agnostic hint ("upgrade the
			// tool that reads this lockfile"), so name the concrete command
			// for this binary here.
			if errors.Is(err, parserlock.ErrFutureVersion) {
				return nil, fmt.Errorf("reading %s: %w; run `gh extension upgrade gh-actions-lock` to update", parserlock.Path, err)
			}
			// Any other parse failure (corrupt YAML, unknown fields, a
			// dependency entry missing a required key) is surfaced, not
			// swallowed. Treating it as empty here would silently discard
			// the user's pins and overwrite them on the next save.
			return nil, fmt.Errorf("%w: %s: %v", ErrCorruptLockfile, parserlock.Path, err)
		}
	case errors.Is(err, os.ErrNotExist):
		file = parserlock.File{Version: parserlock.Version}
	default:
		return nil, fmt.Errorf("reading %s: %w", parserlock.Path, err)
	}

	if file.Version == "" {
		file.Version = parserlock.Version
	}
	if file.Dependencies == nil {
		file.Dependencies = map[string]parserlock.Action{}
	}
	if file.Workflows == nil {
		file.Workflows = map[string][]string{}
	}

	s := &State{
		lockPath: lockfilePath,
		file:     file,
		meta:     meta,
		idCache:  map[string][2]int64{},
	}
	// Normalize on-disk entries to the canonical (lowercased) pin form so any
	// legacy mixed-case keys are rewritten on the next Save.
	normalizedDependencies := make(map[string]parserlock.Action, len(file.Dependencies))
	for pinKey, action := range file.Dependencies {
		pin, ok := parserlock.ParsePin(pinKey)
		if !ok {
			normalizedDependencies[pinKey] = action
			continue
		}
		canon := pin.String()
		normalizedDependencies[canon] = action
		if action.OwnerID != 0 && action.RepoID != 0 {
			// idCache is keyed by lowercase owner/repo to match lookupIDs and the
			// canonical pin reader; mixed-case keys here would silently miss.
			s.idCache[strings.ToLower(pin.Owner+"/"+pin.Repo)] = [2]int64{action.OwnerID, action.RepoID}
		}
	}
	s.file.Dependencies = normalizedDependencies
	for wfKey, deps := range s.file.Workflows {
		changed := false
		normalized := make([]string, len(deps))
		for i, raw := range deps {
			if pin, ok := parserlock.ParsePin(raw); ok {
				canon := pin.String()
				if canon != raw {
					changed = true
				}
				normalized[i] = canon
			} else {
				normalized[i] = raw
			}
		}
		if changed {
			s.file.Workflows[wfKey] = normalized
		}
	}
	return s, nil
}

// File returns the in-memory parser-level lockfile snapshot. Intended for
// consumers that drive the workflow-parser diagnostics engine directly and
// need the whole file (workflow keys + actions metadata) in one shot.
func (s *State) File() parserlock.File {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.file
}

// HasWorkflow reports whether the lockfile's workflows{} map already
// contains an entry for workflowKey. Used by `upgrade --no-onboard` to
// refuse silently onboarding a previously-untracked workflow during a
// Dependabot run.
func (s *State) HasWorkflow(workflowKey string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	_, ok := s.file.Workflows[workflowKey]
	return ok
}

// Get returns the dependencies recorded for workflowKey (e.g.
// ".github/workflows/ci.yml"). Returns nil when the workflow has no entry.
func (s *State) Get(workflowKey string) ([]dep.Dependency, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	deps, ok := s.file.Workflows[workflowKey]
	if !ok {
		return nil, nil
	}
	out := make([]dep.Dependency, 0, len(deps))
	for _, raw := range deps {
		pin, ok := parserlock.ParsePin(raw)
		if !ok {
			return nil, fmt.Errorf("invalid pin %q in %s for workflow %q", raw, parserlock.Path, workflowKey)
		}
		out = append(out, pinToDep(pin))
	}
	return out, nil
}

// AllDeps returns every action entry in the lockfile as a Dependency,
// populated with Tag and Branch inferred from the action's ref field.
// Order is undefined. Intended for callers that need the union of recorded
// pins across all workflows (e.g. seeding resolver caches on startup).
func (s *State) AllDeps() []dep.Dependency {
	s.mu.Lock()
	defer s.mu.Unlock()
	out := make([]dep.Dependency, 0, len(s.file.Dependencies))
	for raw, action := range s.file.Dependencies {
		pin, ok := parserlock.ParsePin(raw)
		if !ok {
			continue
		}
		d := pinToDep(pin)
		d.Tag, d.Branch = parserlock.SplitRef(action.Ref)
		out = append(out, d)
	}
	return out
}

// Set replaces the workflow's direct-dependency entry and upserts the
// per-action metadata for every pin in the resolved closure. The workflow
// entry holds only the action refs that appear in the workflow file itself
// (its direct uses); per-action `uses:` lists encode the transitive graph,
// so a reader walks from each direct pin to reconstruct the full closure —
// the npm/cargo lockfile model.
//
// parentMap is the resolver's child → []parent map (Dependency.Key() form:
// NWO@Ref, without the SHA suffix), as returned by Resolver.ParentMap. Set
// uses it to build per-action `uses:` lists by inversion. Both sides are
// translated into canonical pin keys (NWO@Ref:algo-hex).
//
// directKeys is the set of Dependency.Key() values (NWO@Ref) that the
// workflow file uses directly. It is authoritative for the workflow's
// direct-pin list: a dep is recorded as workflow-direct iff its key is in
// directKeys. This correctly handles deps that are both a direct use and a
// composite-transitive dep (e.g. actions/setup-go used directly and also
// pulled in by a composite) — such a dep has a parent in parentMap but must
// still appear in the workflow's direct list. When directKeys is nil, Set
// falls back to treating any dep with no parent in parentMap as direct.
//
// Resolution of owner/repo numeric IDs happens lazily per NWO and is cached
// for the lifetime of the store.
func (s *State) Set(ctx context.Context, workflowKey string, deps []dep.Dependency, parentMap map[string][]string, directKeys map[string]bool) error {
	// Resolve repo IDs for every unique owner/repo BEFORE taking s.mu so
	// concurrent pin workers don't serialize on the network round-trip.
	// lookupIDs is safe to call without s.mu and dedups in-flight fetches
	// for the same key via singleflight.
	seenRepos := make(map[string]struct{}, len(deps))
	for _, d := range deps {
		pin, err := depToPin(d)
		if err != nil {
			return err
		}
		k := pin.Owner + "/" + pin.Repo
		if _, ok := seenRepos[k]; ok {
			continue
		}
		seenRepos[k] = struct{}{}
		if _, err := s.lookupIDs(ctx, pin.Owner, pin.Repo); err != nil {
			return fmt.Errorf("resolving repo IDs for %s/%s: %w", pin.Owner, pin.Repo, err)
		}
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	directPins := make([]string, 0)
	seenDirect := map[string]bool{}
	// keyToPin: Dependency.Key() (NWO@Ref) → canonical pin (NWO@Ref:algo-hex).
	keyToPin := make(map[string]string, len(deps))
	for _, d := range deps {
		pin, err := depToPin(d)
		if err != nil {
			return err
		}
		pin = pin.Canonical()
		pinKey := pin.String()
		keyToPin[d.Key()] = pinKey
		var isDirect bool
		if directKeys != nil {
			isDirect = directKeys[d.Key()]
		} else {
			_, hasParent := parentMap[d.Key()]
			isDirect = !hasParent
		}
		if isDirect && !seenDirect[pinKey] {
			seenDirect[pinKey] = true
			directPins = append(directPins, pinKey)
		}
	}

	// Invert parentMap (child → parents) into parent → children, in canonical
	// pin-key form. Translate both sides via keyToPin; entries that don't
	// resolve to a known dep are skipped (they were filtered out before
	// reaching the writer).
	parentToChildren := make(map[string]map[string]bool)
	for childDepKey, parents := range parentMap {
		childPin, ok := keyToPin[childDepKey]
		if !ok {
			continue
		}
		for _, parentDepKey := range parents {
			parentPin, ok := keyToPin[parentDepKey]
			if !ok {
				continue
			}
			children, exists := parentToChildren[parentPin]
			if !exists {
				children = make(map[string]bool)
				parentToChildren[parentPin] = children
			}
			children[childPin] = true
		}
	}

	// Now upsert action entries with their per-pin uses lists.
	for _, d := range deps {
		pin, err := depToPin(d)
		if err != nil {
			return err
		}
		pin = pin.Canonical()
		pinKey := pin.String()
		// IDs were pre-resolved above (outside the mutex); read from cache
		// directly so we don't recursively re-acquire s.mu.
		ids, ok := s.idCache[strings.ToLower(pin.Owner+"/"+pin.Repo)]
		if !ok {
			return fmt.Errorf("resolving repo IDs for %s/%s: not in cache after pre-resolve", pin.Owner, pin.Repo)
		}
		// Merge uses: each workflow contributes its own transitive edges.
		// A dep that is a parent in one workflow but direct (no children)
		// in another must not clobber the first workflow's uses list.
		usesSet := make(map[string]bool)
		if children, ok := parentToChildren[pinKey]; ok {
			for c := range children {
				usesSet[c] = true
			}
		}
		// Compute the best ref for this dep: tag > branch. Preserve
		// existing ref from prior Set calls when the dep arrives without
		// discovery metadata (carried unchanged from a previous lockfile).
		ref := parserlock.BestRef(d.Tag, d.Branch)
		if existing, ok := s.file.Dependencies[pinKey]; ok {
			if ref == "" {
				ref = existing.Ref
			}
			for _, u := range existing.Uses {
				usesSet[u] = true
			}
		}
		var uses []string
		if len(usesSet) > 0 {
			uses = make([]string, 0, len(usesSet))
			for c := range usesSet {
				uses = append(uses, c)
			}
			sort.Strings(uses)
		}
		s.file.Dependencies[pinKey] = parserlock.Action{
			Ref:     ref,
			Commit:  pin.Algo + "-" + pin.Hex,
			OwnerID: ids[0],
			RepoID:  ids[1],
			Uses:    uses,
		}
	}
	sort.Strings(directPins)
	s.file.Workflows[workflowKey] = directPins
	return nil
}

// Save persists the lockfile to disk, garbage-collecting orphan action
// entries (pins referenced by no workflow). When the in-memory file is empty
// after GC, the on-disk file is removed.
func (s *State) Save() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	// Mark transitive closure reachable from any workflow as used. Walk the
	// per-action `uses:` graph so deduplicated transitive entries don't get
	// GC'd as orphans.
	used := map[string]bool{}
	var walk func(key string)
	walk = func(key string) {
		if used[key] {
			return
		}
		used[key] = true
		if a, ok := s.file.Dependencies[key]; ok {
			for _, child := range a.Uses {
				walk(child)
			}
		}
	}
	for _, deps := range s.file.Workflows {
		for _, dep := range deps {
			walk(dep)
		}
	}
	for key := range s.file.Dependencies {
		if !used[key] {
			delete(s.file.Dependencies, key)
		}
	}

	full := s.lockPath

	if len(s.file.Dependencies) == 0 && len(s.file.Workflows) == 0 {
		if err := os.Remove(full); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		return nil
	}

	out, err := marshalDeterministic(s.file)
	if err != nil {
		return err
	}
	out = append([]byte(lockfileHeader), out...)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return err
	}
	tmp := full + ".tmp"
	if err := os.WriteFile(tmp, out, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, full)
}

// lookupIDs resolves the (owner, repo) numeric IDs, caching the result.
// Safe to call without s.mu held: cache hits are read under a brief lock,
// and concurrent misses for the same key are coalesced via singleflight
// so we issue at most one network request per repo.
func (s *State) lookupIDs(ctx context.Context, owner, repo string) ([2]int64, error) {
	// Cache key is always lowercase: callers mix canonical (lowercased) and
	// raw NWOs, and we MUST agree across all idCache reads/writes or pins
	// silently miss the cache after pre-resolve.
	key := strings.ToLower(owner + "/" + repo)
	s.mu.Lock()
	if ids, ok := s.idCache[key]; ok {
		s.mu.Unlock()
		return ids, nil
	}
	s.mu.Unlock()

	if s.meta == nil {
		return [2]int64{}, fmt.Errorf("metadata resolver not configured")
	}

	res, err, _ := s.idSF.Do(key, func() (any, error) {
		s.mu.Lock()
		if ids, ok := s.idCache[key]; ok {
			s.mu.Unlock()
			return ids, nil
		}
		s.mu.Unlock()

		ownerID, repoID, err := s.meta.RepoIDs(ctx, owner, repo)
		if err != nil {
			return [2]int64{}, err
		}
		if ownerID == 0 || repoID == 0 {
			return [2]int64{}, fmt.Errorf("metadata resolver returned zero IDs for %s", key)
		}
		ids := [2]int64{ownerID, repoID}
		s.mu.Lock()
		s.idCache[key] = ids
		s.mu.Unlock()
		return ids, nil
	})
	if err != nil {
		return [2]int64{}, err
	}
	return res.([2]int64), nil
}
