package lockfile

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	parserlock "github.com/github/gh-actions-pin/pkg/lockfile"
	"golang.org/x/sync/singleflight"
	"gopkg.in/yaml.v3"
)

// Path is the repo-relative location of the dependency lockfile, as declared
// by the parser package.
const Path = parserlock.Path

// lockfileHeader is prepended to every write of the lockfile. It warns
// humans away from hand-editing and points them at the CLI that owns it.
const lockfileHeader = "# This file is machine-generated by `gh actions-pin`.\n" +
	"# Do not edit by hand; run `gh actions-pin` to update.\n" +
	"# Docs: https://gh.io/actions-lockfile\n"

// MetadataResolver fetches the owner/repo numeric IDs for a NWO. The store
// requires these to populate the dependencies: section on every write.
type MetadataResolver interface {
	RepoIDs(ctx context.Context, owner, repo string) (ownerID, repoID int64, err error)
}

// Store wraps the on-disk dependency lockfile for the current invocation.
// Save garbage-collects orphan
// dependencies: entries — entries still referenced by an out-of-scope workflow are
// preserved, so partial invocations (e.g. `upgrade workflows/foo.yml`) stay
// noop on unrelated workflows.
//
// Store is safe for concurrent use: Set/Save/Get/File/AllDeps/lookupIDs all
// take the same mutex, allowing parallel pin and upgrade workers to share
// a single store instance without external synchronization.
type Store struct {
	mu       sync.Mutex
	repoRoot string
	file     parserlock.File
	meta     MetadataResolver
	idCache  map[string][2]int64
	idSF     singleflight.Group
}

// OpenStore reads the lockfile at repoRoot, returning an empty in-memory file
// when none exists on disk.
func OpenStore(repoRoot string, meta MetadataResolver) (*Store, error) {
	full := filepath.Join(repoRoot, Path)
	contents, err := os.ReadFile(full)

	var file parserlock.File
	switch {
	case err == nil:
		file, err = parserlock.Parse(contents)
		if err != nil {
			// A future-version lockfile (written by a newer binary) must
			// surface to the user — silently overwriting it would destroy
			// pins this binary cannot interpret. Other parse failures
			// (corrupt YAML, unknown fields) are treated as empty so a
			// recoverable lockfile can be rewritten.
			if errors.Is(err, parserlock.ErrFutureVersion) {
				return nil, fmt.Errorf("reading %s: %w", Path, err)
			}
			// Corrupt or unrecognized lockfile — treat as empty and overwrite.
			file = parserlock.File{Version: parserlock.Version}
		}
	case errors.Is(err, os.ErrNotExist):
		file = parserlock.File{Version: parserlock.Version}
	default:
		return nil, fmt.Errorf("reading %s: %w", Path, err)
	}

	if file.Version == "" {
		file.Version = parserlock.Version
	}
	if file.Actions == nil {
		file.Actions = map[string]parserlock.Action{}
	}
	if file.Workflows == nil {
		file.Workflows = map[string][]string{}
	}

	s := &Store{
		repoRoot: repoRoot,
		file:     file,
		meta:     meta,
		idCache:  map[string][2]int64{},
	}
	// Normalize on-disk entries to the canonical (lowercased) pin form so any
	// legacy mixed-case keys are rewritten on the next Save.
	normalizedActions := make(map[string]parserlock.Action, len(file.Actions))
	for pinKey, action := range file.Actions {
		pin, ok := parserlock.ParsePin(pinKey)
		if !ok {
			normalizedActions[pinKey] = action
			continue
		}
		canon := pin.String()
		normalizedActions[canon] = action
		if action.OwnerID != 0 && action.RepoID != 0 {
			// idCache is keyed by lowercase owner/repo to match lookupIDs and the
			// canonical pin reader; mixed-case keys here would silently miss.
			s.idCache[strings.ToLower(pin.Owner+"/"+pin.Repo)] = [2]int64{action.OwnerID, action.RepoID}
		}
	}
	s.file.Actions = normalizedActions
	for wfKey, deps := range s.file.Workflows {
		changed := false
		normalized := make([]string, len(deps))
		for i, raw := range deps {
			if pin, ok := parserlock.ParsePin(raw); ok {
				canon := pin.String()
				if canon != raw {
					changed = true
				}
				normalized[i] = canon
			} else {
				normalized[i] = raw
			}
		}
		if changed {
			s.file.Workflows[wfKey] = normalized
		}
	}
	return s, nil
}

// File returns the in-memory parser-level lockfile snapshot. Intended for
// consumers that drive the workflow-parser diagnostics engine directly and
// need the whole file (workflow keys + actions metadata) in one shot.
func (s *Store) File() parserlock.File {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.file
}

// HasWorkflow reports whether the lockfile's workflows{} map already
// contains an entry for workflowKey. Used by `upgrade --no-onboard` to
// refuse silently onboarding a previously-untracked workflow during a
// Dependabot run.
func (s *Store) HasWorkflow(workflowKey string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	_, ok := s.file.Workflows[workflowKey]
	return ok
}

// Get returns the dependencies recorded for workflowKey (e.g.
// ".github/workflows/ci.yml"). Returns nil when the workflow has no entry.
func (s *Store) Get(workflowKey string) ([]Dependency, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	deps, ok := s.file.Workflows[workflowKey]
	if !ok {
		return nil, nil
	}
	out := make([]Dependency, 0, len(deps))
	for _, raw := range deps {
		pin, ok := parserlock.ParsePin(raw)
		if !ok {
			return nil, fmt.Errorf("invalid pin %q in %s for workflow %q", raw, Path, workflowKey)
		}
		out = append(out, pinToDependency(pin))
	}
	return out, nil
}

// AllDeps returns every action entry in the lockfile as a Dependency,
// populated with Tag and Branch from the action metadata block. Order is
// undefined. Intended for callers that need the union of recorded pins
// across all workflows (e.g. seeding resolver caches on startup).
func (s *Store) AllDeps() []Dependency {
	s.mu.Lock()
	defer s.mu.Unlock()
	out := make([]Dependency, 0, len(s.file.Actions))
	for raw, action := range s.file.Actions {
		pin, ok := parserlock.ParsePin(raw)
		if !ok {
			continue
		}
		d := pinToDependency(pin)
		d.Tag = action.Tag
		d.Branch = action.Branch
		out = append(out, d)
	}
	return out
}

// DirectTracker captures, by dep index, which resolved deps correspond to a
// workflow's direct uses: refs. Build it from the freshly resolved deps
// (before any narrowing/normalization mutates dep.Ref), then read the final
// NWO@Ref direct-key set back with Keys after mutation.
//
// Keys takes the (possibly reassigned) deps slice so callers that swap the
// slice for an index-aligned copy — e.g. PreserveRefs — still resolve to the
// post-mutation refs. The index alignment is the contract: every transform
// between NewDirectTracker and Keys must preserve dep order and length.
//
// Directness is determined by the workflow file's own uses: refs, not by the
// resolver parent map. A dep that is both a direct use and a composite
// transitive dep (e.g. actions/setup-go used directly and also pulled in by a
// composite) has a parent in the parent map but must still be recorded as a
// workflow-direct pin — otherwise it is perpetually re-flagged as not-pinned.
type DirectTracker struct {
	direct []bool
}

// NewDirectTracker records which entries of deps match one of the workflow's
// direct refs, by NWO@Ref, at the deps' current (pre-mutation) refs.
func NewDirectTracker(refs []parserlock.ActionRef, deps []Dependency) DirectTracker {
	want := make(map[string]bool, len(refs))
	for _, ref := range refs {
		want[ref.NWO()+"@"+ref.Ref] = true
	}
	direct := make([]bool, len(deps))
	for i, d := range deps {
		direct[i] = want[d.Key()]
	}
	return DirectTracker{direct: direct}
}

// Keys returns the set of workflow-direct NWO@Ref keys, reading each dep's
// current (post-mutation) Key() from the supplied index-aligned slice.
func (t DirectTracker) Keys(deps []Dependency) map[string]bool {
	out := make(map[string]bool, len(deps))
	for i, d := range deps {
		if i < len(t.direct) && t.direct[i] {
			out[d.Key()] = true
		}
	}
	return out
}

// Set replaces the workflow's direct-dependency entry and upserts the
// per-action metadata for every pin in the resolved closure. The workflow
// entry holds only the action refs that appear in the workflow file itself
// (its direct uses); per-action `uses:` lists encode the transitive graph,
// so a reader walks from each direct pin to reconstruct the full closure —
// the npm/cargo lockfile model.
//
// parentMap is the resolver's child → []parent map (Dependency.Key() form:
// NWO@Ref, without the SHA suffix), as returned by Resolver.ParentMap. Set
// uses it to build per-action `uses:` lists by inversion. Both sides are
// translated into canonical pin keys (NWO@Ref:algo-hex).
//
// directKeys is the set of Dependency.Key() values (NWO@Ref) that the
// workflow file uses directly. It is authoritative for the workflow's
// direct-pin list: a dep is recorded as workflow-direct iff its key is in
// directKeys. This correctly handles deps that are both a direct use and a
// composite-transitive dep (e.g. actions/setup-go used directly and also
// pulled in by a composite) — such a dep has a parent in parentMap but must
// still appear in the workflow's direct list. When directKeys is nil, Set
// falls back to treating any dep with no parent in parentMap as direct.
//
// Resolution of owner/repo numeric IDs happens lazily per NWO and is cached
// for the lifetime of the store.
func (s *Store) Set(ctx context.Context, workflowKey string, deps []Dependency, parentMap map[string][]string, directKeys map[string]bool) error {
	// Resolve repo IDs for every unique owner/repo BEFORE taking s.mu so
	// concurrent pin workers don't serialize on the network round-trip.
	// lookupIDs is safe to call without s.mu and dedups in-flight fetches
	// for the same key via singleflight.
	seenRepos := make(map[string]struct{}, len(deps))
	for _, d := range deps {
		pin, err := dependencyToPin(d)
		if err != nil {
			return err
		}
		k := pin.Owner + "/" + pin.Repo
		if _, ok := seenRepos[k]; ok {
			continue
		}
		seenRepos[k] = struct{}{}
		if _, err := s.lookupIDs(ctx, pin.Owner, pin.Repo); err != nil {
			return fmt.Errorf("resolving repo IDs for %s/%s: %w", pin.Owner, pin.Repo, err)
		}
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	directPins := make([]string, 0)
	seenDirect := map[string]bool{}
	// keyToPin: Dependency.Key() (NWO@Ref) → canonical pin (NWO@Ref:algo-hex).
	keyToPin := make(map[string]string, len(deps))
	for _, d := range deps {
		if d.Branch == "" {
			return fmt.Errorf("%s@%s: branch is required in lockfile metadata; run `gh actions-pin` to populate it", d.NWO, d.Ref)
		}
		pin, err := dependencyToPin(d)
		if err != nil {
			return err
		}
		pin = pin.Canonical()
		pinKey := pin.String()
		keyToPin[d.Key()] = pinKey
		var isDirect bool
		if directKeys != nil {
			isDirect = directKeys[d.Key()]
		} else {
			_, hasParent := parentMap[d.Key()]
			isDirect = !hasParent
		}
		if isDirect && !seenDirect[pinKey] {
			seenDirect[pinKey] = true
			directPins = append(directPins, pinKey)
		}
	}

	// Invert parentMap (child → parents) into parent → children, in canonical
	// pin-key form. Translate both sides via keyToPin; entries that don't
	// resolve to a known dep are skipped (they were filtered out before
	// reaching the writer).
	parentToChildren := make(map[string]map[string]bool)
	for childDepKey, parents := range parentMap {
		childPin, ok := keyToPin[childDepKey]
		if !ok {
			continue
		}
		for _, parentDepKey := range parents {
			parentPin, ok := keyToPin[parentDepKey]
			if !ok {
				continue
			}
			children, exists := parentToChildren[parentPin]
			if !exists {
				children = make(map[string]bool)
				parentToChildren[parentPin] = children
			}
			children[childPin] = true
		}
	}

	// Now upsert action entries with their per-pin uses lists.
	for _, d := range deps {
		pin, err := dependencyToPin(d)
		if err != nil {
			return err
		}
		pin = pin.Canonical()
		pinKey := pin.String()
		// IDs were pre-resolved above (outside the mutex); read from cache
		// directly so we don't recursively re-acquire s.mu.
		ids, ok := s.idCache[strings.ToLower(pin.Owner+"/"+pin.Repo)]
		if !ok {
			return fmt.Errorf("resolving repo IDs for %s/%s: not in cache after pre-resolve", pin.Owner, pin.Repo)
		}
		var uses []string
		if children, ok := parentToChildren[pinKey]; ok && len(children) > 0 {
			uses = make([]string, 0, len(children))
			for c := range children {
				uses = append(uses, c)
			}
			sort.Strings(uses)
		}
		s.file.Actions[pinKey] = parserlock.Action{
			Tag:     d.Tag,
			Branch:  d.Branch,
			Commit:  pin.Algo + "-" + pin.Hex,
			OwnerID: ids[0],
			RepoID:  ids[1],
			Uses:    uses,
		}
	}
	sort.Strings(directPins)
	s.file.Workflows[workflowKey] = directPins
	return nil
}

// Save persists the lockfile to disk, garbage-collecting orphan action
// entries (pins referenced by no workflow). When the in-memory file is empty
// after GC, the on-disk file is removed.
func (s *Store) Save() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	// Mark transitive closure reachable from any workflow as used. Walk the
	// per-action `uses:` graph so deduplicated transitive entries don't get
	// GC'd as orphans.
	used := map[string]bool{}
	var walk func(key string)
	walk = func(key string) {
		if used[key] {
			return
		}
		used[key] = true
		if a, ok := s.file.Actions[key]; ok {
			for _, child := range a.Uses {
				walk(child)
			}
		}
	}
	for _, deps := range s.file.Workflows {
		for _, dep := range deps {
			walk(dep)
		}
	}
	for key := range s.file.Actions {
		if !used[key] {
			delete(s.file.Actions, key)
		}
	}

	full := filepath.Join(s.repoRoot, Path)

	if len(s.file.Actions) == 0 && len(s.file.Workflows) == 0 {
		if err := os.Remove(full); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		return nil
	}

	out, err := marshalDeterministic(s.file)
	if err != nil {
		return err
	}
	out = append([]byte(lockfileHeader), out...)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		return err
	}
	tmp := full + ".tmp"
	if err := os.WriteFile(tmp, out, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, full)
}

// lookupIDs resolves the (owner, repo) numeric IDs, caching the result.
// Safe to call without s.mu held: cache hits are read under a brief lock,
// and concurrent misses for the same key are coalesced via singleflight
// so we issue at most one network request per repo.
func (s *Store) lookupIDs(ctx context.Context, owner, repo string) ([2]int64, error) {
	// Cache key is always lowercase: callers mix canonical (lowercased) and
	// raw NWOs, and we MUST agree across all idCache reads/writes or pins
	// silently miss the cache after pre-resolve.
	key := strings.ToLower(owner + "/" + repo)
	s.mu.Lock()
	if ids, ok := s.idCache[key]; ok {
		s.mu.Unlock()
		return ids, nil
	}
	s.mu.Unlock()

	if s.meta == nil {
		return [2]int64{}, fmt.Errorf("metadata resolver not configured")
	}

	res, err, _ := s.idSF.Do(key, func() (any, error) {
		s.mu.Lock()
		if ids, ok := s.idCache[key]; ok {
			s.mu.Unlock()
			return ids, nil
		}
		s.mu.Unlock()

		ownerID, repoID, err := s.meta.RepoIDs(ctx, owner, repo)
		if err != nil {
			return [2]int64{}, err
		}
		if ownerID == 0 || repoID == 0 {
			return [2]int64{}, fmt.Errorf("metadata resolver returned zero IDs for %s", key)
		}
		ids := [2]int64{ownerID, repoID}
		s.mu.Lock()
		s.idCache[key] = ids
		s.mu.Unlock()
		return ids, nil
	})
	if err != nil {
		return [2]int64{}, err
	}
	return res.([2]int64), nil
}

// WorkflowKeyFromPath converts a workflow path discovered on disk (relative
// to the repo root or cwd) into the repo-relative key used inside the
// lockfile.
func WorkflowKeyFromPath(workflowPath string) string {
	cleaned := filepath.ToSlash(filepath.Clean(workflowPath))
	cleaned = strings.TrimPrefix(cleaned, "./")
	return cleaned
}

// marshalDeterministic emits YAML with stable key ordering. Map keys in Go
// maps are randomized; for a lockfile we want byte-stable output across runs.
//
// All string keys and values whose content is user-supplied (pin strings,
// workflow paths, tag/branch/commit, version) are emitted single-quoted so
// the file round-trips identically regardless of YAML scalar-resolution
// quirks: pin keys carry colons, tags can look like floats ("1.0"), refs
// can collide with YAML 1.1 booleans ("y", "no", "on", "off"). Schema
// field names (version, actions, workflows, tag, branch, …) stay
// unquoted because they're hardcoded and trivially safe.
func marshalDeterministic(file parserlock.File) ([]byte, error) {
	root := &yaml.Node{Kind: yaml.MappingNode}
	addQuotedField(root, "version", file.Version)

	if len(file.Workflows) > 0 {
		keys := make([]string, 0, len(file.Workflows))
		for k := range file.Workflows {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		workflowsNode := &yaml.Node{Kind: yaml.MappingNode}
		for _, k := range keys {
			deps := append([]string(nil), file.Workflows[k]...)
			sort.Strings(deps)
			seq := &yaml.Node{Kind: yaml.SequenceNode}
			for _, d := range deps {
				seq.Content = append(seq.Content, quotedScalar(d))
			}
			workflowsNode.Content = append(workflowsNode.Content,
				quotedScalar(k),
				seq,
			)
		}
		root.Content = append(root.Content,
			plainScalar("workflows"),
			workflowsNode,
		)
	}

	if len(file.Actions) > 0 {
		keys := make([]string, 0, len(file.Actions))
		for k := range file.Actions {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		depsNode := &yaml.Node{Kind: yaml.MappingNode}
		for _, k := range keys {
			a := file.Actions[k]
			entry := &yaml.Node{Kind: yaml.MappingNode}
			if a.Tag != "" {
				addQuotedField(entry, "tag", a.Tag)
			}
			if a.Branch != "" {
				addQuotedField(entry, "branch", a.Branch)
			}
			if a.Commit != "" {
				addQuotedField(entry, "commit", a.Commit)
			}
			addIntField(entry, "owner_id", a.OwnerID)
			addIntField(entry, "repo_id", a.RepoID)
			if len(a.Uses) > 0 {
				uses := append([]string(nil), a.Uses...)
				sort.Strings(uses)
				usesSeq := &yaml.Node{Kind: yaml.SequenceNode}
				for _, u := range uses {
					usesSeq.Content = append(usesSeq.Content, quotedScalar(u))
				}
				entry.Content = append(entry.Content,
					plainScalar("uses"),
					usesSeq,
				)
			}
			depsNode.Content = append(depsNode.Content,
				quotedScalar(k),
				entry,
			)
		}
		root.Content = append(root.Content,
			plainScalar("dependencies"),
			depsNode,
		)
	}

	doc := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}
	return yaml.Marshal(doc)
}

// plainScalar is for hardcoded schema field names (version, actions, …).
func plainScalar(name string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Value: name}
}

// quotedScalar single-quotes user-supplied string values so YAML
// auto-typing can never reinterpret them as numbers, booleans, dates, etc.
func quotedScalar(value string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Style: yaml.SingleQuotedStyle, Value: value}
}

func addQuotedField(parent *yaml.Node, key, value string) {
	parent.Content = append(parent.Content,
		plainScalar(key),
		quotedScalar(value),
	)
}

func addIntField(parent *yaml.Node, key string, value int64) {
	parent.Content = append(parent.Content,
		plainScalar(key),
		&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: fmt.Sprintf("%d", value)},
	)
}
