# frozen_string_literal: true

# Integration scenarios for gh-actions-pin.
#
# Each scenario creates a temporary repo with workflow files and runs the
# binary against it. Some scenarios use a stub HTTP server to simulate
# GitHub API behavior (SSO enforcement, network errors, etc.).
#
# Run:
#   make build && ruby test/integration/run.rb
#   ruby test/integration/run.rb sso   # filter by name

require_relative "harness"

runner = ActionsPin::Integration::Runner.new

# ── Helpers ─────────────────────────────────────────────────────────────

# Minimal workflow YAML that uses a single action.
def simple_workflow(name:, action:)
  <<~YAML
    name: #{name}
    on: workflow_dispatch
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: #{action}
  YAML
end

# Workflow using multiple actions (more realistic).
def multi_action_workflow(name:, actions:)
  steps = actions.map { |a| "      - uses: #{a}" }.join("\n")
  <<~YAML
    name: #{name}
    on: workflow_dispatch
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
    #{steps}
  YAML
end

# Standard lockfile entry for a pinned action.
def lockfile_entry(workflow:, deps:)
  lines = deps.map { |d| "        - '#{d}'" }.join("\n")
  <<~YAML
        '#{workflow}':
    #{lines}
  YAML
end

# Build a complete lockfile from a hash of workflow → deps + dep details.
def build_lockfile(workflows:, dependencies: {})
  wf_section = workflows.map do |wf, deps|
    dep_lines = deps.map { |d| "        - '#{d}'" }.join("\n")
    "    '#{wf}':\n#{dep_lines}"
  end.join("\n")

  dep_section = dependencies.map do |key, attrs|
    attr_lines = attrs.map { |k, v| "        #{k}: '#{v}'" }.join("\n")
    "    '#{key}':\n#{attr_lines}"
  end.join("\n")

  <<~YAML
    # This file is machine-generated by `gh actions-pin`.
    version: 'v0.0.1'
    workflows:
    #{wf_section}
    dependencies:
    #{dep_section}
  YAML
end

# Register a catch-all SSO 403 on both GET and POST.
def sso_403_all(srv)
  [:GET, :POST].each do |method|
    srv.on(method, /.*/) do |_req|
      [
        403,
        {
          "Content-Type" => "application/json",
          "X-GitHub-SSO" => SSO_HEADER_VALUE
        },
        JSON.generate(SSO_ERROR_BODY)
      ]
    end
  end
end

# ── Fixture data ────────────────────────────────────────────────────────

# Real-ish SHA stubs (40 hex chars).
CHECKOUT_SHA = "de0fac2e4500dabe0009e67214ff5f5447ce83dd"
SETUP_GO_SHA = "4a3601121dd01d1626a1e23e37211e3254c1c06c"
CACHE_SHA    = "27d5ce7f107fe9357f9df03efb73ab90386fccae"

SSO_ERROR_BODY = {
  message: "Resource protected by organization SAML enforcement. " \
           "You must grant your OAuth token access to this organization.",
  documentation_url: "https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/"
}

SSO_HEADER_VALUE = 'required; url=https://github.com/orgs/actions/sso?authorization_request=ABCDEF123'

# ════════════════════════════════════════════════════════════════════════
# SCENARIO: Happy path — all actions resolve and pin successfully
# ════════════════════════════════════════════════════════════════════════

runner.scenario(:happy_path) do |s|
  s.workflow "ci.yml", simple_workflow(name: "CI", action: "actions/checkout@v4")

  # The binary needs real GitHub API access for this scenario.
  # Skip if no token is available.
  s.env("GH_TOKEN" => ENV["GH_TOKEN"] || ENV["GITHUB_TOKEN"] || "")

  s.assert_custom do |r|
    token = ENV["GH_TOKEN"] || ENV["GITHUB_TOKEN"] || ""
    if token.empty?
      # Can't run against real API without a token — skip gracefully.
      nil
    else
      s.failures << "expected success" unless r.success?
    end
  end
end

# ════════════════════════════════════════════════════════════════════════
# SCENARIO: Already pinned, all valid — quick lockfile trust path
# ════════════════════════════════════════════════════════════════════════

runner.scenario(:already_pinned_all_valid) do |s|
  # This scenario needs a real GitHub API with valid lockfile entries.
  # The lockfile SHAs must match what the API returns, so it only works
  # against the live API with a valid token. Skip otherwise.
  s.workflow "ci.yml", simple_workflow(name: "CI", action: "actions/checkout@v4")

  s.env("GH_TOKEN" => ENV["GH_TOKEN"] || ENV["GITHUB_TOKEN"] || "")

  s.assert_custom do |r|
    token = ENV["GH_TOKEN"] || ENV["GITHUB_TOKEN"] || ""
    if token.empty?
      nil # skip — no token
    elsif !r.success?
      # Even without a lockfile, first run should succeed by pinning
      s.failures << "expected success, got exit #{r.exit_code}:\n#{r.output}"
    end
  end
end

# ════════════════════════════════════════════════════════════════════════
# SCENARIO: SSO failure — actions org requires SAML authorization
# ════════════════════════════════════════════════════════════════════════
#
# This is the core scenario from this session: a token lacking SSO
# authorization for the "actions" org gets 403s with X-GitHub-SSO header.
# The output should:
#   - Use ✗ (error icon) for unresolved actions
#   - Show the clean reason without "resolution failed:" prefix
#   - Dedup identical SSO errors across multiple actions
#   - Surface "Authorize in your web browser:  <url>" with the real
#     authorization_request= URL from the X-GitHub-SSO header

runner.scenario(:sso_auth_failure) do |s|
  # Multiple actions from the same org — all will fail with SSO
  s.workflow "ci.yml", multi_action_workflow(
    name: "CI",
    actions: [
      "actions/checkout@v4",
      "actions/setup-go@v5",
      "actions/cache@v4"
    ]
  )

  s.stub_server do |srv|
    sso_403_all(srv)
  end

  s.assert_failure
  s.assert_output_contains(
    "could not be resolved",                           # error header
    "actions/checkout",                                 # action listed
    "actions/setup-go",                                 # action listed
    "actions/cache",                                    # action listed
    "SAML enforcement",                                 # clean reason from API body
  )
  s.assert_output_excludes(
    "resolution failed:",                               # prefix should be stripped
  )
  # The SSO authorization URL from X-GitHub-SSO header should be surfaced
  s.assert_output_contains(
    "Authorize in your web browser",
  )
end

# ════════════════════════════════════════════════════════════════════════
# SCENARIO: SSO failure deduplication — many actions, same root cause
# ════════════════════════════════════════════════════════════════════════
#
# 11 actions from the same org all fail with SSO enforcement. The output
# should show the SSO reason exactly once, not 11 times.

runner.scenario(:sso_dedup) do |s|
  actions = %w[
    actions/checkout@v4
    actions/setup-go@v5
    actions/cache@v4
    actions/upload-artifact@v4
    actions/download-artifact@v4
    actions/setup-python@v5
    actions/setup-dotnet@v4
    actions/setup-node@v4
    actions/create-github-app-token@v1
    actions/github-script@v7
    actions/stale@v9
  ]

  s.workflow "ci.yml", multi_action_workflow(name: "CI", actions: actions[0..5])
  s.workflow "deploy.yml", multi_action_workflow(name: "Deploy", actions: actions[4..10])

  s.stub_server do |srv|
    sso_403_all(srv)
  end

  s.env("GH_TOKEN" => "gho_fake_sso_test_token")

  s.assert_failure
  # Reason should appear exactly once (deduped)
  s.assert_custom do |r|
    count = r.output.scan("SAML enforcement").size
    if count > 1
      s.failures << "SSO reason appeared #{count} times, expected 1 (dedup failed)\n#{r.output}"
    elsif count == 0
      s.failures << "SSO reason not found in output:\n#{r.output}"
    end
  end

  # All actions should still be listed
  s.assert_output_contains("actions/checkout", "actions/stale", "actions/github-script")
end

# ════════════════════════════════════════════════════════════════════════
# SCENARIO: Mixed failures — SSO + repo not found
# ════════════════════════════════════════════════════════════════════════
#
# One action fails with SSO, another with a different error. They should
# NOT be deduped together.

runner.scenario(:mixed_failures) do |s|
  s.workflow "ci.yml", multi_action_workflow(
    name: "CI",
    actions: [
      "actions/checkout@v4",
      "octo-org/private-action@v1"
    ]
  )

  s.stub_server do |srv|
    # GraphQL always returns SSO 403 (the resolve path starts with GQL)
    srv.on(:POST, /.*/) do |_req|
      [
        403,
        {
          "Content-Type" => "application/json",
          "X-GitHub-SSO" => SSO_HEADER_VALUE
        },
        JSON.generate(SSO_ERROR_BODY)
      ]
    end

    # actions/* routes → SSO 403
    srv.on(:GET, %r{/repos/actions/}) do |_req|
      [
        403,
        {
          "Content-Type" => "application/json",
          "X-GitHub-SSO" => SSO_HEADER_VALUE
        },
        JSON.generate(SSO_ERROR_BODY)
      ]
    end

    # octo-org/* routes → 404 not found
    srv.on(:GET, %r{/repos/octo-org/}) do |_req|
      [
        404,
        { "Content-Type" => "application/json" },
        JSON.generate({ message: "Not Found" })
      ]
    end
  end

  s.env("GH_TOKEN" => "gho_fake_mixed_test_token")

  s.assert_failure
  s.assert_output_contains(
    "could not be resolved",
    "actions/checkout",
    "octo-org/private-action",
  )
end

# ════════════════════════════════════════════════════════════════════════
# SCENARIO: Rescan with inconclusive — should fail, not show "All valid"
# ════════════════════════════════════════════════════════════════════════
#
# When --rescan is used and API calls fail (e.g. SSO), the reachability
# check is inconclusive. The run should exit non-zero and NOT print
# "✓ All N workflows valid".

runner.scenario(:rescan_inconclusive_fails) do |s|
  s.workflow "ci.yml", simple_workflow(name: "CI", action: "actions/checkout@v4")

  s.lockfile build_lockfile(
    workflows: {
      ".github/workflows/ci.yml" => [
        "actions/checkout@v4:sha1-#{CHECKOUT_SHA}"
      ]
    },
    dependencies: {
      "actions/checkout@v4:sha1-#{CHECKOUT_SHA}" => {
        "tag" => "v4",
        "branch" => "main",
        "commit" => "sha1-#{CHECKOUT_SHA}",
        "owner_id" => "44036562",
        "repo_id" => "197814629"
      }
    }
  )

  s.args("--rescan")

  s.stub_server do |srv|
    sso_403_all(srv)
  end

  s.env("GH_TOKEN" => "gho_fake_rescan_token")

  s.assert_failure
  s.assert_output_excludes("All", "valid")
end

# ════════════════════════════════════════════════════════════════════════
# SCENARIO: Unresolved uses error icon (✗), not warning (!)
# ════════════════════════════════════════════════════════════════════════

runner.scenario(:unresolved_uses_error_icon) do |s|
  s.workflow "ci.yml", simple_workflow(name: "CI", action: "actions/checkout@v4")

  s.stub_server do |srv|
    sso_403_all(srv)
  end

  s.env("GH_TOKEN" => "gho_fake_icon_test_token")

  # In headless mode (non-TTY), icons are stripped. We verify the error
  # semantics by checking for the error-level "could not be resolved"
  # phrasing (TermError) rather than the ✗ glyph.
  s.assert_output_contains("could not be resolved")
  s.assert_failure
end

# ════════════════════════════════════════════════════════════════════════
# SCENARIO: Resolution record path is shown
# ════════════════════════════════════════════════════════════════════════

runner.scenario(:resolution_record_shown) do |s|
  s.workflow "ci.yml", simple_workflow(name: "CI", action: "actions/checkout@v4")

  s.stub_server do |srv|
    sso_403_all(srv)
  end

  s.env("GH_TOKEN" => "gho_fake_record_test_token")

  # Should show the resolution record path with - prefix (skip icon)
  s.assert_output_contains("Resolution record:")
end

# ════════════════════════════════════════════════════════════════════════
# SCENARIO: No workflow files found — graceful error
# ════════════════════════════════════════════════════════════════════════

runner.scenario(:no_workflows) do |s|
  # Don't add any workflow files — empty repo
  s.env("GH_TOKEN" => "gho_fake_no_workflows_token")

  s.assert_failure
end

# ════════════════════════════════════════════════════════════════════════
# SCENARIO: Prefix stripping — "resolution failed: NWO@ref:" cleaned
# ════════════════════════════════════════════════════════════════════════
#
# The raw error reason from the resolver wraps the message in
# "resolution failed: actions/checkout@v4.3.1: <actual error>".
# The CLI should strip these prefixes and show only the clean error.
# This is validated by the unit tests, but we confirm end-to-end here.

runner.scenario(:prefix_stripping) do |s|
  s.workflow "ci.yml", simple_workflow(name: "CI", action: "actions/checkout@v4")

  s.stub_server do |srv|
    sso_403_all(srv)
  end

  s.env("GH_TOKEN" => "gho_fake_prefix_test_token")

  s.assert_failure
  # The "resolution failed:" wrapper should NOT appear in output
  s.assert_output_excludes("resolution failed:")
  # The clean error should appear
  s.assert_output_contains("SAML enforcement")
end

# ── Run ─────────────────────────────────────────────────────────────────
runner.run(filter: ARGV[0])
