# frozen_string_literal: true

# Integration scenarios for gh-actions-lock.
#
# Scenarios are defined in the shared catalog (test/scenarios/catalog.yml)
# and hydrated here with stub server wiring and custom assertions. Both
# the Ruby integration harness and the Go test suite consume the same
# catalog, ensuring the scenario matrix stays in sync.
#
# Run:
#   make build && ruby test/integration/run.rb
#   ruby test/integration/run.rb sso          # filter by name
#   ruby test/integration/run.rb --live       # live repo tests only
#   ruby test/integration/run.rb --stub       # stub tests only
#   ruby test/integration/run.rb --smoke      # smoke tests only

require_relative "harness"

runner = ActionsPin::Integration::Runner.new

# ── Helpers ─────────────────────────────────────────────────────────────

# Minimal workflow YAML that uses a single action.
def simple_workflow(name:, action:)
  <<~YAML
    # This workflow is managed by gh actions-lock.

    name: #{name}
    on: workflow_dispatch
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: #{action}
  YAML
end

# Workflow using multiple actions (more realistic).
def multi_action_workflow(name:, actions:)
  steps = actions.map { |a| "      - uses: #{a}" }.join("\n")
  <<~YAML
    # This workflow is managed by gh actions-lock.

    name: #{name}
    on: workflow_dispatch
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
    #{steps}
  YAML
end

# Build a complete lockfile from a hash of workflow → deps + dep details.
def build_lockfile(workflows:, dependencies: {})
  wf_section = workflows.map do |wf, deps|
    dep_lines = deps.map { |d| "        - '#{d}'" }.join("\n")
    "    '#{wf}':\n#{dep_lines}"
  end.join("\n")

  dep_section = dependencies.map do |key, attrs|
    attr_lines = attrs.map do |k, v|
      formatted = v.is_a?(Integer) ? v.to_s : "'#{v}'"
      "        #{k}: #{formatted}"
    end.join("\n")
    "    '#{key}':\n#{attr_lines}"
  end.join("\n")

  <<~YAML
    # This file is machine-generated by `gh actions-lock`.
    # Do not edit by hand; run `gh actions-lock` to update.
    # Docs: https://gh.io/actions-lockfile
    version: 'v0.0.2'
    workflows:
    #{wf_section}
    dependencies:
    #{dep_section}
  YAML
end

# Register a catch-all SSO 403 on both GET and POST.
def sso_403_all(srv)
  [:GET, :POST].each do |method|
    srv.on(method, /.*/) do |_req|
      [
        403,
        {
          "Content-Type" => "application/json",
          "X-GitHub-SSO" => SSO_HEADER_VALUE
        },
        JSON.generate(SSO_ERROR_BODY)
      ]
    end
  end
end

# Register a catch-all that returns the given status with a JSON body.
def error_all(srv, status, body)
  [:GET, :POST].each do |method|
    srv.on(method, /.*/) do |_req|
      [
        status,
        { "Content-Type" => "application/json" },
        JSON.generate(body)
      ]
    end
  end
end

# Hydrate a scenario from catalog workflow fixtures.
def hydrate_workflows(s, workflows)
  return if workflows.nil? || workflows.empty?

  workflows.each do |path, spec|
    if spec.is_a?(Hash) && spec["raw"]
      s.workflow(path, spec["raw"])
    elsif spec.is_a?(Hash) && spec["actions"]
      if spec["actions"].size == 1
        s.workflow(path, simple_workflow(name: spec["name"] || "CI", action: spec["actions"].first))
      else
        s.workflow(path, multi_action_workflow(name: spec["name"] || "CI", actions: spec["actions"]))
      end
    end
  end
end

# Hydrate assertions from catalog expect block.
def hydrate_assertions(s, expect, needs_token: false)
  if expect["exit"]
    if expect["exit"] == 0
      s.assert_success
    else
      s.assert_failure
    end
  end

  if expect["exit_any"]
    s.assert_custom do |r|
      unless expect["exit_any"].include?(r.exit_code)
        s.failures << "expected exit #{expect['exit_any'].inspect}, got #{r.exit_code}:\n#{r.output}"
      end
    end
  end

  if expect["output_contains"]
    s.assert_output_contains(*expect["output_contains"])
  end

  if expect["output_excludes"]
    s.assert_output_excludes(*expect["output_excludes"])
  end

  if expect["stdout_is_json"]
    s.assert_custom do |r|
      begin
        JSON.parse(r.stdout)
      rescue JSON::ParserError => e
        s.failures << "stdout is not valid JSON: #{e.message}\n#{r.stdout.slice(0, 200)}"
      end
    end
  end

  if expect["stdout_contains"]
    s.assert_stdout_contains(*expect["stdout_contains"])
  end

  if expect["lockfile_exists"]
    s.assert_lockfile_exists
  end

  if expect["lockfile_comment_matches"]
    s.assert_lockfile_comment_matches(expect["lockfile_comment_matches"])
  end

  if expect["lockfile_comment_excludes"]
    s.assert_lockfile_comment_excludes(expect["lockfile_comment_excludes"])
  end

  if expect["lockfile_contains"]
    s.assert_lockfile_contains(*expect["lockfile_contains"])
  end

  if expect["lockfile_deps_cover_direct"]
    s.assert_lockfile_deps_cover_direct
    # Also verify lockfile workflow refs match the actual YAML files.
    s.assert_lockfile_workflow_coherence
  end

  if expect["lockfile_deps_cover_indirect"]
    s.assert_lockfile_deps_cover_indirect
  end

  if expect["lockfile_golden"]
    golden_path = File.expand_path("../../scenarios/testdata/#{expect["lockfile_golden"]}", __FILE__)
    s.assert_custom do |r|
      lockpath = File.join(r.dir, ".github", "workflows", "actions.lock")
      got = File.read(lockpath) rescue ""
      want = File.read(golden_path)
      if got != want
        s.failures << "lockfile does not match golden #{expect["lockfile_golden"]}\n--- got ---\n#{got}\n--- want ---\n#{want}"
      end
    end
  end

  if expect["stdout_excludes"]
    expect["stdout_excludes"].each do |pat|
      s.assert_custom do |r|
        if r.stdout.include?(pat)
          s.failures << "stdout should not contain #{pat.inspect}\n  in:\n#{r.stdout.lines.first(20).map { |l| "    #{l}" }.join}"
        end
      end
    end
  end

  if expect["jq"]
    expect["jq"].each do |check|
      expr = check["expr"]
      s.assert_custom do |r|
        begin
          parsed = JSON.parse(r.stdout)
        rescue JSON::ParserError => e
          s.failures << "jq #{expr}: stdout is not valid JSON: #{e.message}"
          next
        end

        # Shell out to jq for the expression
        result = IO.popen(["jq", "-r", expr], "r+") do |io|
          io.write(JSON.generate(parsed))
          io.close_write
          io.read
        end
        result = result&.strip

        if check.key?("equals")
          expected = check["equals"].to_s
          unless result == expected
            s.failures << "jq '#{expr}' = #{result.inspect}, expected #{expected.inspect}"
          end
        end

        if check.key?("contains")
          unless result&.include?(check["contains"].to_s)
            s.failures << "jq '#{expr}' = #{result.inspect}, expected to contain #{check['contains'].inspect}"
          end
        end

        if check.key?("not_equals")
          if result == check["not_equals"].to_s
            s.failures << "jq '#{expr}' = #{result.inspect}, expected not to equal #{check['not_equals'].inspect}"
          end
        end

        if check.key?("matches")
          unless result&.match?(Regexp.new(check["matches"]))
            s.failures << "jq '#{expr}' = #{result.inspect}, expected to match /#{check['matches']}/"
          end
        end

        if check.key?("gt") || check.key?("greater_than")
          val = result.to_f
          threshold = (check["gt"] || check["greater_than"]).to_f
          unless val > threshold
            s.failures << "jq '#{expr}' = #{result}, expected > #{threshold}"
          end
        end
      end
    end
  end

  if expect["golden_json"]
    s.assert_custom do |r|
      begin
        actual = JSON.parse(r.stdout)
      rescue JSON::ParserError => e
        s.failures << "golden_json: stdout is not valid JSON: #{e.message}"
        next
      end

      expected = expect["golden_json"]
      # cli_version is a build-time stamp that varies between
      # `go build` (devel) and module-aware builds (v0.0.0-...).
      # Ignore it so CI and local runs compare identically.
      [expected, actual].each { |h| h.delete("cli_version") if h.is_a?(Hash) }
      diff = golden_json_diff(expected, actual, "")
      diff.each { |d| s.failures << "golden_json mismatch: #{d}" }
    end
  end

  # Token-required scenarios skip gracefully without a token
  if needs_token
    s.needs_token(true)
  end
end

# Deep comparison for golden JSON bodies. Returns an array of diff
# descriptions (empty = match). Compares structure and values but
# ignores key order within objects. Array order IS significant.
def golden_json_diff(expected, actual, path)
  diffs = []
  case expected
  when Hash
    unless actual.is_a?(Hash)
      return ["#{path}: expected object, got #{actual.class.name.downcase}"]
    end
    (expected.keys | actual.keys).sort.each do |k|
      child_path = path.empty? ? k : "#{path}.#{k}"
      unless expected.key?(k)
        diffs << "#{child_path}: unexpected key in actual"
        next
      end
      unless actual.key?(k)
        diffs << "#{child_path}: missing in actual"
        next
      end
      diffs.concat(golden_json_diff(expected[k], actual[k], child_path))
    end
  when Array
    unless actual.is_a?(Array)
      return ["#{path}: expected array, got #{actual.class.name.downcase}"]
    end
    if expected.size != actual.size
      diffs << "#{path}: expected #{expected.size} items, got #{actual.size}"
    end
    [expected.size, actual.size].min.times do |i|
      diffs.concat(golden_json_diff(expected[i], actual[i], "#{path}[#{i}]"))
    end
  else
    if expected != actual
      diffs << "#{path}: expected #{expected.inspect}, got #{actual.inspect}"
    end
  end
  diffs
end

# ── Fixture data ────────────────────────────────────────────────────────

CHECKOUT_SHA      = "de0fac2e4500dabe0009e67214ff5f5447ce83dd"
SETUP_GO_SHA      = "4a3601121dd01d1626a1e23e37211e3254c1c06c"
CACHE_SHA         = "27d5ce7f107fe9357f9df03efb73ab90386fccae"
MAIN_BRANCH_SHA   = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
FORGERY_LIVE_SHA  = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
FORGERY_MERGE_BASE = "cccccccccccccccccccccccccccccccccccccccc"

SSO_ERROR_BODY = {
  message: "Resource protected by organization SAML enforcement. " \
           "You must grant your OAuth token access to this organization.",
  documentation_url: "https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/"
}

SSO_HEADER_VALUE = 'required; url=https://github.com/orgs/actions/sso?authorization_request=ABCDEF123'

# ── Lockfile templates ──────────────────────────────────────────────────

LOCKFILE_TEMPLATES = {
  "pinned_checkout" => -> {
    build_lockfile(
      workflows: {
        ".github/workflows/ci.yml" => [
          "actions/checkout@v4"
        ]
      },
      dependencies: {
        "actions/checkout@v4" => {
          "ref" => "v4",
          "commit" => "sha1-#{CHECKOUT_SHA}",
          "owner_id" => 44036562,
          "repo_id" => 197814629
        }
      }
    )
  },
  # Same as pinned_checkout but the dep key reflects a non-narrowed v4
  # (imprecise) lock — sticky precision should keep it as v4 on re-pin.
  "pinned_checkout_v4_imprecise" => -> {
    build_lockfile(
      workflows: {
        ".github/workflows/ci.yml" => [
          "actions/checkout@v4"
        ]
      },
      dependencies: {
        "actions/checkout@v4" => {
          "ref" => "v4",
          "commit" => "sha1-#{CHECKOUT_SHA}",
          "owner_id" => 44036562,
          "repo_id" => 197814629
        }
      }
    )
  },
  # Lockfile with a fully-narrowed dep key (v4.2.0) — represents a
  # workflow that was previously onboarded with default narrowing.
  "pinned_checkout_full" => -> {
    build_lockfile(
      workflows: {
        ".github/workflows/ci.yml" => [
          "actions/checkout@v4.2.0"
        ]
      },
      dependencies: {
        "actions/checkout@v4.2.0" => {
          "ref" => "v4.2.0",
          "commit" => "sha1-#{CHECKOUT_SHA}",
          "owner_id" => 44036562,
          "repo_id" => 197814629
        }
      }
    )
  },
  # Lockfile with a branch-ref dep key (main) — represents a workflow
  # onboarded with --no-narrow that should be narrowed on re-pin.
  "pinned_checkout_main" => -> {
    build_lockfile(
      workflows: {
        ".github/workflows/ci.yml" => [
          "actions/checkout@main"
        ]
      },
      dependencies: {
        "actions/checkout@main" => {
          "ref" => "main",
          "commit" => "sha1-#{CHECKOUT_SHA}",
          "owner_id" => 44036562,
          "repo_id" => 197814629
        }
      }
    )
  },
  # Lockfile with a deliberately stale SHA that is NOT an ancestor of
  # current v4. Used to trigger lockfile-forgery and test --accept-moved.
  "forgery_stale_checkout" => -> {
    build_lockfile(
      workflows: {
        ".github/workflows/ci.yml" => [
          "actions/checkout@v4"
        ]
      },
      dependencies: {
        "actions/checkout@v4" => {
          "ref" => "v4",
          "commit" => "sha1-0000000000000000000000000000000000000000",
          "owner_id" => 44036562,
          "repo_id" => 197814629
        }
      }
    )
  },
  "future_version" => -> {
    <<~YAML
      # This file is machine-generated by `gh actions-lock`.
      version: 'v99.99.99'
      workflows: {}
      dependencies: {}
    YAML
  }
}

# ── Shared stub helpers for detection scenarios ────────────────────────

# Wire common REST routes for actions/checkout repo metadata.
def checkout_repo_rest(srv)
  # GET /api/v3/repos/actions/checkout — repo metadata
  srv.on(:GET, %r{/repos/actions/checkout$}) do |_req|
    [200, { "Content-Type" => "application/json" },
     JSON.generate({
       default_branch: "main",
       visibility: "public",
       pushed_at: "2024-01-01T00:00:00Z",
       id: 197_814_629,
       owner: { id: 44_036_562 }
     })]
  end

  # GET .../tags — tag list for narrowing/reverse lookup
  srv.on(:GET, %r{/repos/actions/checkout/tags}) do |_req|
    [200, { "Content-Type" => "application/json" },
     JSON.generate([
       { name: "v4", commit: { sha: CHECKOUT_SHA } },
       { name: "v4.2.2", commit: { sha: CHECKOUT_SHA } },
       { name: "v4.2.1", commit: { sha: "1111111111111111111111111111111111111111" } },
       { name: "v3", commit: { sha: "2222222222222222222222222222222222222222" } }
     ])]
  end

  # GET .../git/ref/heads/main — branch head SHA
  srv.on(:GET, %r{/repos/actions/checkout/git/ref/heads/main$}) do |_req|
    [200, { "Content-Type" => "application/json" },
     JSON.generate({ ref: "refs/heads/main", object: { sha: MAIN_BRANCH_SHA, type: "commit" } })]
  end

  # GET .../branches?protected=true — no protected branches
  srv.on(:GET, %r{/repos/actions/checkout/branches\?protected=true}) do |_req|
    [200, { "Content-Type" => "application/json" }, "[]"]
  end

  # GET .../branches — only main
  srv.on(:GET, %r{/repos/actions/checkout/branches}) do |_req|
    [200, { "Content-Type" => "application/json" },
     JSON.generate([{ name: "main", commit: { sha: MAIN_BRANCH_SHA }, protected: false }])]
  end

  # GET .../git/matching-refs/heads/* — no release branches
  srv.on(:GET, %r{/repos/actions/checkout/git/matching-refs/}) do |_req|
    [200, { "Content-Type" => "application/json" }, "[]"]
  end
end

# GraphQL handler that resolves actions/checkout@v4 to the given SHA
# and returns DIVERGED for all reachability checks.
# GraphQL handler that resolves actions/checkout@v4 to a DIFFERENT SHA
# (simulating ref-moved), so the forgery ancestry check kicks in.
def checkout_graphql_forgery(srv)
  srv.on(:POST, %r{/graphql$}) do |req|
    body = JSON.parse(req.body) rescue {}
    query = body["query"] || ""

    if query.include?("expression")
      # ResolveActionFiles — return a different SHA (ref moved)
      [200, { "Content-Type" => "application/json" },
       JSON.generate({ data: { a0: {
         nameWithOwner: "actions/checkout",
         object: { oid: FORGERY_LIVE_SHA, file: { object: { text: "name: Checkout\ndescription: Checkout\n" } } }
       } } })]
    elsif query.include?("compare")
      # Reachability — irrelevant for forgery path but keep it working
      repo_data = {}
      query.scan(/b(\d+):/).flatten.each { |i| repo_data["b#{i}"] = { compare: { status: "BEHIND" } } }
      [200, { "Content-Type" => "application/json" },
       JSON.generate({ data: { repo: repo_data } })]
    else
      [200, { "Content-Type" => "application/json" }, JSON.generate({ data: {} })]
    end
  end
end

# ── Stub server wiring per scenario ────────────────────────────────────
#
# Maps scenario names to blocks that wire up the stub server. Scenarios
# not listed here either use no stub or rely on catalog-level config.

STUB_WIRING = {
  # SSO scenarios: catch-all 403 with X-GitHub-SSO header
  sso_auth_failure: ->(s) {
    s.stub_server { |srv| sso_403_all(srv) }
  },
  sso_anon_fallback: ->(s) {
    # Authenticated requests (with Authorization header) get SAML 403.
    # Anonymous requests (no Authorization) succeed — simulating public repo.
    fake_sha = "a" * 40
    s.stub_server do |srv|
      # GraphQL always uses auth → return SAML error.
      srv.on(:POST, /.*/) do |req|
        [403, { "Content-Type" => "application/json", "X-GitHub-SSO" => SSO_HEADER_VALUE },
         JSON.generate(SSO_ERROR_BODY)]
      end

      # GET: if Authorization present → SAML 403; otherwise → anon success.
      srv.on(:GET, /.*/) do |req|
        if req["Authorization"] && !req["Authorization"].empty?
          [403, { "Content-Type" => "application/json", "X-GitHub-SSO" => SSO_HEADER_VALUE },
           JSON.generate(SSO_ERROR_BODY)]
        elsif req.path.include?("/orgs/")
          # Probe: org is publicly visible.
          [200, { "Content-Type" => "application/json" },
           JSON.generate({ login: "actions", id: 44036562 })]
        elsif req.path.include?("/commits/")
          [200, { "Content-Type" => "application/json" },
           JSON.generate({ sha: fake_sha })]
        elsif req.path.include?("/contents/")
          [200, { "Content-Type" => "text/plain" },
           "name: 'Checkout'\ndescription: 'Checkout'\ninputs: {}\nruns:\n  using: node20\n  main: dist/index.js\n"]
        elsif req.path.include?("/branches")
          [200, { "Content-Type" => "application/json" },
           JSON.generate([{ name: "main", commit: { sha: fake_sha }, protected: true }])]
        elsif req.path.include?("/tags")
          [200, { "Content-Type" => "application/json" },
           JSON.generate([{ name: "v4", commit: { sha: fake_sha } }])]
        elsif req.path.match?(%r{/repos/actions/checkout$})
          [200, { "Content-Type" => "application/json" },
           JSON.generate({ default_branch: "main", visibility: "public", pushed_at: "2024-01-01T00:00:00Z", id: 1, owner: { id: 44036562 } })]
        elsif req.path.include?("/compare/")
          [200, { "Content-Type" => "application/json" },
           JSON.generate({ status: "behind", merge_base_commit: { sha: fake_sha } })]
        elsif req.path.include?("/releases")
          [200, { "Content-Type" => "application/json" },
           JSON.generate([{ tag_name: "v4", published_at: "2024-01-01T00:00:00Z", immutable: false }])]
        else
          [404, { "Content-Type" => "application/json" }, JSON.generate({ message: "Not Found" })]
        end
      end

      # HEAD for the probe.
      srv.on(:HEAD, /.*/) do |req|
        if req["Authorization"] && !req["Authorization"].empty?
          [403, { "Content-Type" => "application/json" }, ""]
        else
          [200, { "Content-Type" => "application/json" }, ""]
        end
      end
    end
    s.env("GH_TOKEN" => "gho_fake_sso_fallback_token")
  },
  sso_dedup: ->(s) {
    s.stub_server { |srv| sso_403_all(srv) }
    s.env("GH_TOKEN" => "gho_fake_sso_test_token")
  },
  mixed_failures: ->(s) {
    s.stub_server do |srv|
      srv.on(:POST, /.*/) do |_req|
        [403, { "Content-Type" => "application/json", "X-GitHub-SSO" => SSO_HEADER_VALUE },
         JSON.generate(SSO_ERROR_BODY)]
      end
      srv.on(:GET, %r{/repos/actions/}) do |_req|
        [403, { "Content-Type" => "application/json", "X-GitHub-SSO" => SSO_HEADER_VALUE },
         JSON.generate(SSO_ERROR_BODY)]
      end
      srv.on(:GET, %r{/repos/octo-org/}) do |_req|
        [404, { "Content-Type" => "application/json" }, JSON.generate({ message: "Not Found" })]
      end
    end
    s.env("GH_TOKEN" => "gho_fake_mixed_test_token")
  },
  rescan_inconclusive_fails: ->(s) {
    s.stub_server { |srv| sso_403_all(srv) }
    s.env("GH_TOKEN" => "gho_fake_rescan_token")
  },

  # Error icon / record / prefix scenarios: SSO 403 as a reliable failure trigger
  unresolved_uses_error_icon: ->(s) {
    s.stub_server { |srv| sso_403_all(srv) }
    s.env("GH_TOKEN" => "gho_fake_icon_test_token")
  },
  resolution_record_shown: ->(s) {
    s.stub_server { |srv| sso_403_all(srv) }
    s.env("GH_TOKEN" => "gho_fake_record_test_token")
  },
  prefix_stripping: ->(s) {
    s.stub_server { |srv| sso_403_all(srv) }
    s.env("GH_TOKEN" => "gho_fake_prefix_test_token")
  },

  # API error scenarios
  api_404_not_found: ->(s) {
    s.stub_server do |srv|
      error_all(srv, 404, { message: "Not Found" })
    end
    s.env("GH_TOKEN" => "gho_fake_404_token")
  },
  api_rate_limit_429: ->(s) {
    s.stub_server do |srv|
      [:GET, :POST].each do |method|
        srv.on(method, /.*/) do |_req|
          [429, {
            "Content-Type" => "application/json",
            "Retry-After" => "1",
            "X-RateLimit-Remaining" => "0",
            "X-RateLimit-Reset" => (Time.now.to_i + 2).to_s
          }, JSON.generate({ message: "API rate limit exceeded" })]
        end
      end
    end
    s.env("GH_TOKEN" => "gho_fake_ratelimit_token")
  },
  api_server_error_500: ->(s) {
    s.stub_server do |srv|
      error_all(srv, 500, { message: "Internal Server Error" })
    end
    s.env("GH_TOKEN" => "gho_fake_500_token")
  },
  api_unauthorized_401: ->(s) {
    s.stub_server do |srv|
      error_all(srv, 401, { message: "Bad credentials" })
    end
    s.env("GH_TOKEN" => "gho_fake_401_token")
  },

  # JSON output scenarios (stub — deterministic output)
  json_output_findings: ->(s) {
    s.stub_server { |srv| sso_403_all(srv) }
    s.env("GH_TOKEN" => "gho_fake_json_token")
  },
  no_fix_json_combined: ->(s) {
    s.stub_server { |srv| sso_403_all(srv) }
    s.env("GH_TOKEN" => "gho_fake_json_combined_token")
  },

  # Detection scenarios: lockfile forgery (pinned SHA not ancestor of live SHA)
  dbot_forgery_blocks: ->(s) {
    s.stub_server do |srv|
      checkout_graphql_forgery(srv)
      checkout_repo_rest(srv)
      # Compare API: merge_base != pinned SHA → forgery
      srv.on(:GET, %r{/repos/actions/checkout/compare/}) do |_req|
        [200, { "Content-Type" => "application/json" },
         JSON.generate({
           status: "diverged",
           merge_base_commit: { sha: FORGERY_MERGE_BASE }
         })]
      end
    end
    s.env("GH_TOKEN" => "gho_fake_forgery_token")
  },

  # Orphaned bare-SHA pin: GraphQL resolves the repo but the commit object is
  # null and there is NO GraphQL error — a clean null, the definitive
  # "unreachable" signal. Routes to unresolvable-commit (error/high).
  dbot_unresolvable_blocks: ->(s) {
    s.stub_server do |srv|
      srv.on(:POST, %r{/graphql$}) do |_req|
        [200, { "Content-Type" => "application/json" },
         JSON.generate({ data: { a0: { nameWithOwner: "actions/checkout", object: nil } } })]
      end
      checkout_repo_rest(srv)
    end
    s.env("GH_TOKEN" => "gho_fake_unresolvable_token")
  },

  # Transient: same null object, but accompanied by a path-scoped GraphQL
  # error on the alias (rate limit). The transient-safety guard withholds the
  # definitive sentinel, so this routes to reachability-unverified (error/low),
  # NOT unresolvable-commit.
  dbot_inconclusive_blocks: ->(s) {
    s.stub_server do |srv|
      srv.on(:POST, %r{/graphql$}) do |_req|
        [200, { "Content-Type" => "application/json" },
         JSON.generate({
           data: { a0: { nameWithOwner: "actions/checkout", object: nil } },
           errors: [{ type: "RATE_LIMITED", message: "API rate limit exceeded", path: ["a0"] }]
         })]
      end
      checkout_repo_rest(srv)
    end
    s.env("GH_TOKEN" => "gho_fake_inconclusive_token")
  },

  # Symbolic ref moved to a different SHA, but the Compare API is down (5xx)
  # so ancestry can't be decided → ancestry-unknown (error/medium).
  dbot_ancestry_unknown_blocks: ->(s) {
    s.stub_server do |srv|
      checkout_graphql_forgery(srv)
      checkout_repo_rest(srv)
      srv.on(:GET, %r{/repos/actions/checkout/compare/}) do |_req|
        [500, { "Content-Type" => "application/json" }, JSON.generate({ message: "Server Error" })]
      end
    end
    s.env("GH_TOKEN" => "gho_fake_ancestry_token")
  },

  # Negative control: live SHA matches the pin, ancestry is a no-op → clean.
  dbot_clean_passes: ->(s) {
    s.stub_server do |srv|
      srv.on(:POST, %r{/graphql$}) do |_req|
        [200, { "Content-Type" => "application/json" },
         JSON.generate({ data: { a0: {
           nameWithOwner: "actions/checkout",
           object: { oid: CHECKOUT_SHA, file: { object: { text: "name: Checkout\ndescription: Checkout\n" } } }
         } } })]
      end
      checkout_repo_rest(srv)
    end
    s.env("GH_TOKEN" => "gho_fake_clean_token")
  },
}

# ── Custom assertion wiring ─────────────────────────────────────────────

CUSTOM_ASSERTIONS = {
  sso_dedup: ->(s) {
    s.assert_custom do |r|
      count = r.output.scan("SAML enforcement").size
      if count > 1
        s.failures << "SSO reason appeared #{count} times, expected 1 (dedup failed)\n#{r.output}"
      elsif count == 0
        s.failures << "SSO reason not found in output:\n#{r.output}"
      end
    end
  },
}

# ═══════════════════════════════════════════════════════════════════════
# Load and hydrate scenarios from the shared catalog
# ═══════════════════════════════════════════════════════════════════════

catalog = ActionsPin::Integration::Catalog.load

catalog["scenarios"].each do |spec|
  name = spec["name"].to_sym
  needs_token = spec["needs_token"]
  needs_stub = spec["needs_stub"]
  skip_reason = spec["skip"]
  fixtures = spec["fixtures"] || {}
  expect = spec["expect"] || {}
  flags = spec["flags"] || []
  live_repo = spec["live_repo"]

  runner.scenario(name) do |s|
    s.category = spec["category"] || "other"
    s.description = spec["description"]
    s.expect_spec = expect
    s.fixture_spec = fixtures
    s.input_spec = spec["input"]
    s.skip_reason = skip_reason

    # Hydrate workflow fixtures
    hydrate_workflows(s, fixtures["workflows"])

    # Hydrate lockfile
    if fixtures["lockfile"]
      s.lockfile(fixtures["lockfile"])
    elsif fixtures["lockfile_template"]
      tmpl = LOCKFILE_TEMPLATES[fixtures["lockfile_template"]]
      s.lockfile(tmpl.call) if tmpl
    end

    # CLI flags
    s.args(*flags) unless flags.empty?

    # Token-required scenarios: use explicit GH_TOKEN if set, otherwise
    # fall back to gh CLI auth (go-gh resolves this automatically).
    # Only skip if neither is available.
    if needs_token
      token = ENV["GH_TOKEN"] || ENV["GITHUB_TOKEN"]
      if token
        s.env("GH_TOKEN" => token)
      else
        # Check gh CLI auth — the binary will use this automatically,
        # but we need to verify it exists so we can skip gracefully.
        gh_token = `gh auth token 2>/dev/null`.strip
        if gh_token.empty?
          # No auth at all — scenario will be skipped at run time
        end
        # Don't set GH_TOKEN — let go-gh resolve from gh CLI config
      end
    end

    # Live repo scenarios clone and run against a real repo
    if live_repo
      s.live_repo(live_repo)
    end

    # Delete lockfile before running (for migration/schema tests)
    if fixtures["delete_lockfile"]
      s.setup do |dir|
        lockpath = File.join(dir, ".github", "workflows", "actions.lock")
        File.delete(lockpath) if File.exist?(lockpath)
      end
    end

    # Stub server wiring
    if STUB_WIRING[name]
      STUB_WIRING[name].call(s)
    elsif needs_stub && !STUB_WIRING[name]
      # Default stub: SSO 403 (reliable failure trigger)
      s.stub_server { |srv| sso_403_all(srv) }
      s.env("GH_TOKEN" => "gho_fake_default_stub_token")
    end

    # Custom assertions
    CUSTOM_ASSERTIONS[name]&.call(s)

    # Standard assertions from catalog
    hydrate_assertions(s, expect, needs_token: needs_token)
  end
end

# ── Run ─────────────────────────────────────────────────────────────────

tag_filter = nil
tag_flags = []
tag_flags << "live"      if ARGV.delete("--live")
tag_flags << "stub"      if ARGV.delete("--stub")
tag_flags << "smoke"     if ARGV.delete("--smoke")
tag_flags << "real_repo" if ARGV.delete("--real")

if tag_flags.size > 1
  $stderr.puts "Error: only one tag filter allowed, got: #{tag_flags.map { |t| "--#{t}" }.join(', ')}"
  exit 1
end
tag_filter = tag_flags.first

# --profile [dir] enables trace/CPU/HTTP profiling per scenario
profile_idx = ARGV.index("--profile")
if profile_idx
  ARGV.delete_at(profile_idx)
  runner.profile_dir = File.expand_path(ARGV.delete_at(profile_idx) || "profiles")
  FileUtils.mkdir_p(runner.profile_dir)
end

golden_category = nil
golden_idx = ARGV.index("--golden-update")
if golden_idx
  ARGV.delete_at(golden_idx)
  golden_category = ARGV.delete_at(golden_idx) || "dependabot"
end

if ARGV.delete("--shell") || ARGV.delete("-i")
  runner.shell
elsif ARGV.delete("--matrix")
  # removed — was only a read-only matrix view, not a test runner
  $stderr.puts "Error: --matrix was removed. Use `make test-integration` or `make test-stub`."
  exit 1
elsif golden_category
  runner.golden_update(category: golden_category, catalog: catalog)
else
  runner.run(filter: ARGV[0], tag_filter: tag_filter, catalog: catalog)
end
