name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: OIDC Setup for goproxy
        uses: github/setup-goproxy@v1.1.0
      - uses: actions/checkout@v5.0.1
      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
      - name: gofmt
        run: |
          unformatted="$(gofmt -l .)"
          if [ -n "$unformatted" ]; then
            echo "These files are not gofmt-clean:"
            echo "$unformatted"
            exit 1
          fi
      - run: go vet ./...
      - run: go test -race -count=1 ./...

  integration-stub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: OIDC Setup for goproxy
        uses: github/setup-goproxy@v1.1.0
      - uses: actions/checkout@v5.0.1
      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
      - name: Install Ruby
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq ruby
          ruby --version
      - run: make build
      - run: make test-stub

  integration-live:
    runs-on: ubuntu-latest
    # Separate job so flakes don't block merge
    continue-on-error: true
    permissions:
      contents: read
      id-token: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: OIDC Setup for goproxy
        uses: github/setup-goproxy@v1.1.0
      - uses: actions/checkout@v5.0.1
      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
      - name: Install Ruby
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq ruby
          ruby --version
      - run: make build
      - run: make test-integration

  lockfile-lint:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      id-token: write
    steps:
      - name: OIDC Setup for goproxy
        uses: github/setup-goproxy@v1.1.0
      - uses: actions/checkout@v5.0.1
      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
      - run: make build

      - name: Check lockfile is in sync
        run: ./script/lockfile-lint.sh ./gh-actions-lock
        env:
          GH_TOKEN: ${{ github.token }}
