name: test

on:
  pull_request:
  push:
    branches:
      - main
  permissions:
    id-token: write # for setup-goproxy
    contents: read

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
     - name: OIDC Setup for goproxy
        uses: github/setup-goproxy@5e60e1074d42316dfe2949ebf9a92bf77b24645b # v1.1.0
      - uses: actions/checkout@v5.0.1
      - uses: actions/setup-go@v6.4.0
        with:
          go-version-file: go.mod
      - run: go test ./...
